site_name: MEDIUM
nav:
    - Pré-rastreabilidade:
        - Definição: pre-rastreabilidade/pre-rastreabilidade.md
        - 5W2H:  pre-rastreabilidade/5w2h.md
        - Richpicture:  pre-rastreabilidade/richpicture.md
        - Argumentação:  pre-rastreabilidade/argumentacao.md
    - Elicitação:
        - Brainstormings: elicitacao/brainstormings.md
        - Introspecções: elicitacao/introspeccao.md
        - Storytelling: elicitacao/storytelling.md
        - StoryBoard: elicitacao/storyboards.md
        - Lista de requisitos: elicitacao/lista-req.md
        - Priorização-Moscow: elicitacao/priorizacao-moscow.md
        - Priorização-Lista de Dependências: elicitacao/priorizacao-dependencias.md
        - Priorização-FTF: elicitacao/priorizacao-ftf.md
    - Modelagem:
        - Cenários: modelagem/cenarios.md
        - Léxicos:  modelagem/lexicos.md
        - Casos de uso:  modelagem/user_case.md
        - Especificações: modelagem/especificacoes.md
        - Especificação Suplementar: modelagem/especificacao_suplementar.md
        - Backlog do Produto: modelagem/product_backlog.md
        - Backlog das Sprints: modelagem/sprints_backlog.md
        - NFR: modelagem/nfrs.md
        - I*: modelagem/i*.md
    - Análise:
        - Inspeção Backlog do produto: analise/product_backlog.md
        - Inspeção Cenários: analise/verificacao_cenarios.md
        - Inspeção I*: analise/verificacao_istars.md
        - Inspeção storytelling: analise/verificacao_storytelling.md
        - Inspeção Especificações: analise/verificacao_especificacoes.md
        - Inspeção Especificações Suplementares: analise/verificacao_especificacao_suplementar.md
        - Inspeção NFR: analise/verificacao_NFR.md
        - Inspeção RichPicure: analise/verificacao_RichPicture.md
        - Inspeção 5W2H: analise/5w2h.md
        - Inspeção User Cases: analise/user_cases.md
        - Inspeção StoryBoard: analise/verificacao_storybord.md
    - Pós-rastreabilidade:
        - Baseline: baseline.md
        - Forward From: pos-rastreabilidade/forward_from.md
        - Backward From: pos-rastreabilidade/backward_from.md
        - Telas das Funcionalidades: pos-rastreabilidade/telas_das_funcionalidades.md
    - Atas: atas-reuniao.md
theme: journal
