site_name: MEDIUM-Requisitos(2019) 
nav:
    - Home: index.md
    - Baseline: baseline.md
    - Pré-rastreabilidade:
        - Definição: pre-rastreabilidade/pre-rastreabilidade.md
        - 5W2H:  pre-rastreabilidade/5w2h.md
        - Richpicture:  pre-rastreabilidade/richpicture.md
        - Argumentação:  pre-rastreabilidade/argumentacao.md
    - Elicitação de requisitos:
        - Brainstormings: elicitacao/brainstormings.md
        - Introspecções: elicitacao/introspeccao.md
        - Storytelling: elicitacao/storytelling.md
        - StoryBord: elicitacao/storybords.md
        - Lista de requisitos: elicitacao/lista-req.md
        - Priorização-Moscow: elicitacao/priorizacao-moscow.md
        - Priorização-Lista de Dependências: elicitacao/priorizacao-dependencias.md
        - Priorização-FTF: elicitacao/priorizacao-ftf.md
    - Modelagem:
        - Cenários: modelagem/cenarios.md
        - Léxicos:  modelagem/lexicos.md
        
    - Atas de reunião: atas-reuniao.md
theme: readthedocs
extra_css: [extra.css]
