theme: jekyll-theme-minimal
description: Repositório destinado a documentação dos modelos usados durante o processo de Engenharia de Requisitos, dentro do escopo da disciplina de Engenharia de Requisitos da Universidade de Brasília.
logo: ../images/medium-logo.png
show_downloads: false
navigation:
  - title: Home
    url: index
  - title: Pré-rastreabilidade
    url: pre-rastreabilidade
